### ISSUE TITLE
[Help]: Unable to check in code. Dont have permission gaidp-gen-ai-dudes

### ISSUE THREAD

**Issue by rahulsurgithub** [ewfx/help#287]
### Challenge

Gen AI-Based Data Profiling

### Team Name

https://github.com/ewfx/gaidp-gen-ai-dudes

### What happened?

You don't have permissions to push to "ewfx/gaidp-gen-ai-dudes" on GitHub. Would you like to create a fork and push to it instead?

### I have read the FAQs

- [x] I agree

**Comment by tech2avinash** [comment]
Resolved. Please check now

**Comment by rahulsurgithub** [comment]
Still not working

[cid:0025a61d-3dfa-4007-82ff-bc0cdb21a158]
________________________________
