### ISSUE TITLE
[Help]:  Unable to push in my repo from my personal account: Team Name - UAIEnthusiasts. Please provide access

### ISSUE THREAD

**Issue by eliusmamun** [ewfx/help#294]
### Challenge

Gen AI Orchestrator for Email and Document Triage/Routing

### Team Name

https://github.com/ewfx/gaied-u-ai-enthusiasts

### What happened?

Unable to push the code

### I have read the FAQs

- [x] I agree

**Comment by tech2avinash** [comment]
Resolved. Please check now

**Comment by eliusmamun** [comment]
Pushed just now . Still getting this - remote: Permission to ewfx/gaied-u-ai-enthusiasts.git denied to eliusmamun. unable to access 'https://github.com/ewfx/gaied-u-ai-enthusiasts.git/': The requested URL returned error: 403

@tech2avinash

**Comment by lochgeo** [comment]
New Invite sent - please accept to get edit access. Once you have access, you can add your team mates

**Comment by eliusmamun** [comment]
Have accepted the invitaion still i am getting 
 Authentication failed for 'https://github.com/ewfx/gaied-u-ai-enthusiasts.git/ @tech2avinash @lochgeo

**Comment by eliusmamun** [comment]
remote: Permission to ewfx/gaied-u-ai-enthusiasts.git denied to eliusmamun. unable to access 'https://github.com/ewfx/gaied-u-ai-enthusiasts.git/': The requested URL returned error: 403
